# -*- coding: utf-8 -*-
"""smart_hire.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sHugikNmqpORhbq2_7sRUlBUtCQbJitw
"""

!pip install gradio spacy PyPDF2 scikit-learn pandas
!python -m spacy download en_core_web_sm

import gradio as gr
import pandas as pd
import spacy
from PyPDF2 import PdfReader
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import io

# Load NLP model
nlp = spacy.load("en_core_web_sm")

def extract_text_from_pdf(file):
    # Gradio sends a file object; we read it
    pdf_reader = PdfReader(file)
    text = ""
    for page in pdf_reader.pages:
        text += page.extract_text() or ""
    return text

def process_and_rank(job_description, resume_files):
    if not job_description or not resume_files:
        return "Please provide both a Job Description and at least one Resume."

    # 1. Prepare data
    resume_texts = []
    resume_names = []

    for file in resume_files:
        # Extract name from file path or object
        name = file.name.split('/')[-1]
        text = extract_text_from_pdf(file)
        resume_texts.append(text)
        resume_names.append(name)

    # 2. Add JD to the list for vectorization
    all_texts = [job_description] + resume_texts

    # 3. Calculate Similarity
    vectorizer = TfidfVectorizer(stop_words='english')
    tfidf_matrix = vectorizer.fit_transform(all_texts)

    # Compare first row (JD) with the rest (Resumes)
    scores = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:]).flatten()

    # 4. Create Leaderboard
    results = pd.DataFrame({
        "Candidate Name": resume_names,
        "Match Score (%)": [round(s * 100, 2) for s in scores]
    })

    # Sort by highest score
    return results.sort_values(by="Match Score (%)", ascending=False)

def smart_hire_app(jd, resumes):
    # Call our backend function
    leaderboard = process_and_rank(jd, resumes)
    return leaderboard

# Create the UI
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🚀 Smart Hire: AI Resume Screener")
    gr.Markdown("Upload multiple resumes and a job description to find the best talent instantly.")

    with gr.Row():
        with gr.Column():
            jd_input = gr.Textbox(label="Job Description", placeholder="Paste the job requirements here...", lines=10)
            resume_input = gr.File(label="Upload Resumes (PDF)", file_count="multiple", file_types=[".pdf"])
            submit_btn = gr.Button("Rank Candidates", variant="primary")

        with gr.Column():
            output_table = gr.DataFrame(label="Candidate Rankings")

    submit_btn.click(fn=smart_hire_app, inputs=[jd_input, resume_input], outputs=output_table)

# Launch in Colab
demo.launch(debug=True)

import gradio as gr
import pandas as pd
from PyPDF2 import PdfReader
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# --- Backend Logic ---

def extract_text(file_path):
    text = ""
    try:
        reader = PdfReader(file_path)
        for page in reader.pages:
            text += page.extract_text() or ""
    except:
        return ""
    return text

def check_plagiarism(resumes_data):
    """Compares resumes against each other to find matches."""
    if len(resumes_data) < 2:
        return ["No duplicates (Only one resume)"] * len(resumes_data)

    texts = [r['text'] for r in resumes_data]
    tfidf = TfidfVectorizer().fit_transform(texts)
    matrix = cosine_similarity(tfidf)

    flags = []
    for i in range(len(resumes_data)):
        # Find highest similarity with any OTHER resume
        others = [matrix[i][j] for j in range(len(resumes_data)) if i != j]
        max_sim = max(others) if others else 0
        if max_sim > 0.8:
            flags.append(f"⚠️ HIGH ({int(max_sim*100)}%)")
        elif max_sim > 0.5:
            flags.append(f"🟡 MODERATE ({int(max_sim*100)}%)")
        else:
            flags.append("✅ Low")
    return flags

def process_hiring(jd, files):
    if not jd or not files:
        return pd.DataFrame(), None

    resumes_data = []
    for f in files:
        resumes_data.append({
            "name": f.name.split('/')[-1],
            "path": f.name,
            "text": extract_text(f.name)
        })

    # Calculate JD Match
    all_texts = [jd] + [r['text'] for r in resumes_data]
    vectorizer = TfidfVectorizer(stop_words='english')
    tfidf_matrix = vectorizer.fit_transform(all_texts)
    scores = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:]).flatten()

    # Calculate Plagiarism
    plagiarism_report = check_plagiarism(resumes_data)

    # Create DataFrame
    df = pd.DataFrame({
        "Rank": range(1, len(files) + 1),
        "Candidate Name": [r['name'] for r in resumes_data],
        "Match Score (%)": [round(s * 100, 2) for s in scores],
        "Plagiarism Risk": plagiarism_report,
        "File_Path": [r['path'] for r in resumes_data] # Hidden helper column
    }).sort_values(by="Match Score (%)", ascending=False)

    # Reset rank after sorting
    df["Rank"] = range(1, len(df) + 1)
    return df

# --- UI Layout ---

with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🏆 Smart Hire Pro: Screening & Plagiarism Guard")

    with gr.Row():
        with gr.Column(scale=1):
            jd_input = gr.Textbox(label="Step 1: Paste Job Description", lines=8)
            file_input = gr.File(label="Step 2: Upload Resumes", file_count="multiple", type="filepath")
            run_btn = gr.Button("Analyze Candidates", variant="primary")

        with gr.Column(scale=2):
            gr.Markdown("### Step 3: Candidate Leaderboard")
            gr.Markdown("*Click a row to preview the resume below*")
            results_table = gr.Dataframe(
                headers=["Rank", "Candidate Name", "Match Score (%)", "Plagiarism Risk"],
                interactive=False
            )

    with gr.Row():
        pdf_viewer = gr.File(label="Resume Preview (Click a name above)", interactive=False)

    # State to keep track of the full dataframe including hidden paths
    full_data_state = gr.State()

    def on_analyze(jd, files):
        df = process_hiring(jd, files)
        # Display table without the 'File_Path' column to keep UI clean
        return df, df.drop(columns=["File_Path"])

    def get_file_on_click(df_full, evt: gr.SelectData):
        # evt.index[0] gives the row index clicked
        row_idx = evt.index[0]
        file_path = df_full.iloc[row_idx]["File_Path"]
        return file_path

    run_btn.click(on_analyze, [jd_input, file_input], [full_data_state, results_table])
    results_table.select(get_file_on_click, [full_data_state], pdf_viewer)

demo.launch(debug=True)

import re
import spacy
from spacy.matcher import Matcher

# This is the line your code is missing!
nlp = spacy.load("en_core_web_sm")
# Now initialize the matcher
matcher = Matcher(nlp.vocab)
# Initialize Matcher for Name Extraction
matcher = Matcher(nlp.vocab)

def extract_contact_info(text):
    # 1. Extract Email
    email_pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
    emails = re.findall(email_pattern, text)
    email = emails[0] if emails else "Not Found"

    # 2. Extract Phone (Supports formats: +91..., (123)..., 123-456..., etc.)
    phone_pattern = r'[\+\(]?[1-9][0-9 .\-\(\)]{8,}[0-9]'
    phones = re.findall(phone_pattern, text)
    phone = phones[0] if phones else "Not Found"

    # 3. Extract Name using SpaCy Matcher (Looking for Proper Nouns)
    doc = nlp(text[:500]) # Scan only the first 500 characters (header area)
    name = "Not Found"

    # Pattern: Two or three consecutive proper nouns (FirstName Middle LastName)
    patterns = [[{'POS': 'PROPN'}, {'POS': 'PROPN'}],
                [{'POS': 'PROPN'}, {'POS': 'PROPN'}, {'POS': 'PROPN'}]]
    matcher.add("NAME", patterns)
    matches = matcher(doc)

    if matches:
        # Get the first match found
        match_id, start, end = matches[0]
        name = doc[start:end].text

    return name, email, phone

def process_hiring(jd, files):
    resumes_data = []
    for f in files:
        text = extract_text(f.name)
        name, email, phone = extract_contact_info(text) # Our new feature!

        resumes_data.append({
            "extracted_name": name,
            "email": email,
            "phone": phone,
            "path": f.name,
            "text": text
        })

    # ... (Keep previous Similarity and Plagiarism logic here) ...

    # Final Table Structure
    df = pd.DataFrame({
        "Rank": range(1, len(files) + 1),
        "Candidate (Extracted)": [r['extracted_name'] for r in resumes_data],
        "Email": [r['email'] for r in resumes_data],
        "Phone": [r['phone'] for r in resumes_data],
        "Match Score (%)": scores_list, # From previous step
        "Plagiarism Risk": plagiarism_report,
        "File_Path": [r['path'] for r in resumes_data]
    }).sort_values(by="Match Score (%)", ascending=False)

    return df

import gradio as gr
import pandas as pd
import spacy
import re
import os
from PyPDF2 import PdfReader
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# 1. Setup NLP
try:
    nlp = spacy.load("en_core_web_sm")
except:
    !python -m spacy download en_core_web_sm
    nlp = spacy.load("en_core_web_sm")

# 2. Extraction Logic Functions
def extract_text(file_path):
    text = ""
    try:
        reader = PdfReader(file_path)
        for page in reader.pages:
            text += page.extract_text() or ""
    except Exception as e:
        return ""
    return text

def parse_resume(text):
    # Email Extraction
    email = re.findall(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', text)

    # Phone Extraction (Common patterns)
    phone = re.findall(r'[\+\(]?[1-9][0-9 .\-\(\)]{8,}[0-9]', text)

    # Name Extraction using SpaCy Entity Recognition
    # We look at the first 300 characters as names are usually at the top
    doc = nlp(text[:300])
    name = "Not Detected"
    for ent in doc.ents:
        if ent.label_ == "PERSON":
            name = ent.text
            break

    return {
        "name": name,
        "email": email[0] if email else "N/A",
        "phone": phone[0] if phone else "N/A"
    }

def check_plagiarism(texts):
    if len(texts) < 2: return ["Low"] * len(texts)
    tfidf = TfidfVectorizer().fit_transform(texts)
    matrix = cosine_similarity(tfidf)
    risks = []
    for i in range(len(texts)):
        # Check similarity with others, excluding itself
        sim_scores = [matrix[i][j] for j in range(len(texts)) if i != j]
        max_score = max(sim_scores) if sim_scores else 0
        if max_score > 0.8: risks.append(f"🚩 High ({int(max_score*100)}%)")
        elif max_score > 0.5: risks.append(f"⚠️ Mod ({int(max_score*100)}%)")
        else: risks.append("✅ Low")
    return risks

# 3. Main Processing for Gradio
def start_screening(jd, files):
    if not jd or not files:
        return pd.DataFrame(), None

    resumes_list = []
    for f in files:
        raw_text = extract_text(f.name)
        info = parse_resume(raw_text)
        resumes_list.append({
            "name": info["name"],
            "email": info["email"],
            "phone": info["phone"],
            "text": raw_text,
            "filename": os.path.basename(f.name),
            "path": f.name
        })

    # Ranking Logic (TF-IDF)
    all_texts = [jd] + [r['text'] for r in resumes_list]
    vectorizer = TfidfVectorizer(stop_words='english')
    tfidf_matrix = vectorizer.fit_transform(all_texts)
    scores = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:]).flatten()

    # Plagiarism Logic
    plagiarism_results = check_plagiarism([r['text'] for r in resumes_list])

    # Build Dataframe
    df = pd.DataFrame({
        "Candidate Name": [r['name'] for r in resumes_list],
        "Contact Email": [r['email'] for r in resumes_list],
        "Phone": [r['phone'] for r in resumes_list],
        "Match Score (%)": [round(s * 100, 1) for s in scores],
        "Plagiarism": plagiarism_results,
        "Original_File": [r['filename'] for r in resumes_list],
        "Hidden_Path": [r['path'] for r in resumes_list] # Used for clicking
    }).sort_values(by="Match Score (%)", ascending=False)

    return df, df.drop(columns=["Hidden_Path"])

# 4. Gradio Interface Construction
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🚀 Smart Hire: AI Multi-Feature Screener")

    with gr.Row():
        with gr.Column(scale=1):
            jd_input = gr.Textbox(label="Job Description", lines=7, placeholder="Paste requirements here...")
            file_input = gr.File(label="Upload Resumes (PDF)", file_count="multiple", type="filepath")
            run_btn = gr.Button("⚡ Analyze & Rank", variant="primary")

        with gr.Column(scale=2):
            gr.Markdown("### Candidate Leaderboard")
            # This state stores the hidden paths so we can click them
            full_data_state = gr.State()
            results_table = gr.Dataframe(
                headers=["Candidate Name", "Contact Email", "Phone", "Match Score (%)", "Plagiarism", "Original_File"],
                interactive=False
            )

    with gr.Row():
        pdf_view = gr.File(label="Quick Preview (Select a row above)", interactive=False)

    # Event Listeners
    run_btn.click(
        fn=start_screening,
        inputs=[jd_input, file_input],
        outputs=[full_data_state, results_table]
    )

    def get_file_path(df_full, evt: gr.SelectData):
        # Index into the full dataframe using the clicked row index
        return df_full.iloc[evt.index[0]]["Hidden_Path"]

    results_table.select(get_file_path, [full_data_state], pdf_view)

demo.launch(debug=True)
